import datetime
from fpdf import FPDF


def _safe(text: str) -> str:
    """Sanitize text for Helvetica (latin-1 range). Replaces common Unicode chars with ASCII equivalents."""
    if not text:
        return ""
    replacements = {
        "\u2014": "-",   # em dash
        "\u2013": "-",   # en dash
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2022": "*",   # bullet
        "\u2026": "...", # ellipsis
        "\u00b0": "deg", # degree sign
        "\u00ae": "(R)", # registered
        "\u00a9": "(C)", # copyright
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Final fallback: drop anything still outside latin-1
    return text.encode("latin-1", errors="replace").decode("latin-1")


class NewsOpsPDF(FPDF):
    def __init__(self, session_id, timestamp_str=None):
        super().__init__()
        self.session_id = _safe(str(session_id))
        self.timestamp_str = timestamp_str or datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.alias_nb_pages()

    def header(self):
        # Draw premium header banner
        self.set_fill_color(15, 23, 42)  # Very dark slate #0f172a
        self.rect(0, 0, 210, 24, "F")

        # Border accent line
        self.set_draw_color(99, 102, 241)  # Indigo-500
        self.set_line_width(1.5)
        self.line(0, 24, 210, 24)

        # Header Text
        self.set_text_color(255, 255, 255)
        self.set_font("helvetica", "B", 12)
        self.set_xy(12, 7)
        self.cell(0, 10, "NewsOps Intelligence Report", ln=0, align="L")

        self.set_font("helvetica", "", 8)
        self.set_xy(12, 7)
        self.cell(186, 10,
                  _safe(f"Session: #{self.session_id}   |   Generated: {self.timestamp_str}"),
                  ln=0, align="R")

        self.set_line_width(0.2)  # reset line width
        self.ln(22)

    def footer(self):
        self.set_y(-18)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(100, 116, 139)  # Slate-500

        # Top border for footer
        self.set_draw_color(226, 232, 240)  # Slate-200
        self.set_line_width(0.5)
        self.line(12, self.get_y() - 2, 198, self.get_y() - 2)

        self.set_x(12)
        self.cell(0, 10, "Generated by NewsOps - AI-powered intelligence system", 0, 0, "L")
        self.set_x(12)
        self.cell(186, 10, f"Page {self.page_no()}/{{nb}}", 0, 0, "R")


def generate_session_pdf(session_dict, artifacts_list) -> bytes:
    # 1. Parse session info
    session_id = session_dict.get("id") or "N/A"
    domain = (session_dict.get("domain") or "general").upper()

    # Format generated time
    timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 2. Extract master brief and agent times
    mb = {}
    agent_times = []

    for a in artifacts_list:
        # Support both ORM objects and plain dicts
        a_type = getattr(a, "artifact_type", None) or (a.get("artifact_type") if isinstance(a, dict) else None)
        a_agent = getattr(a, "agent_name", None) or (a.get("agent_name") if isinstance(a, dict) else None)
        a_duration = getattr(a, "duration_seconds", None) or (a.get("duration_seconds") if isinstance(a, dict) else None)
        a_content = getattr(a, "content", None) or (a.get("content") if isinstance(a, dict) else None)

        if a_type == "master_brief":
            mb = a_content or {}

        if a_agent and a_duration is not None:
            if not any(item["agent"] == a_agent for item in agent_times):
                agent_times.append({
                    "agent": a_agent,
                    "time": f"{float(a_duration):.2f}s"
                })

    if not mb:
        mb = {
            "insight": session_dict.get("insight") or session_dict.get("input_preview") or "No insight summary available.",
            "severity": 5,
            "severity_label": "Medium",
            "confidence_label": "Medium",
            "kpis_affected": [],
            "top_action": {},
            "alternative_actions": []
        }

    # Setup document
    pdf = NewsOpsPDF(session_id, timestamp_str)
    pdf.add_page()

    # ── Helper: section header with indigo side-bar ─────────────────────────
    def draw_section_header(title):
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(15, 23, 42)

        x, y = pdf.get_x(), pdf.get_y()
        pdf.set_fill_color(99, 102, 241)  # Indigo-500
        pdf.rect(x, y + 1, 3, 12, "F")

        pdf.set_x(x + 6)
        pdf.cell(0, 14, _safe(title), ln=1)
        pdf.ln(2)

    # ──────────────────────────────────────────────────────────────────────────
    # Section 1: Executive Summary
    # ──────────────────────────────────────────────────────────────────────────
    draw_section_header("Section 1 - Executive Summary")

    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.set_line_width(0.5)

    start_y = pdf.get_y()
    pdf.rect(12, start_y, 186, 22, "FD")

    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.set_xy(16, start_y + 3)
    pdf.cell(40, 6, "DOMAIN:")
    pdf.cell(50, 6, "SEVERITY SCORE:")
    pdf.cell(50, 6, "CONFIDENCE LEVEL:")

    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.set_xy(16, start_y + 11)
    pdf.cell(40, 6, _safe(domain))

    severity_val = mb.get("severity", 0)
    severity_lbl = mb.get("severity_label", "Medium")
    pdf.set_font("helvetica", "B", 10)
    if severity_val >= 7:
        pdf.set_text_color(239, 68, 68)
    elif severity_val >= 5:
        pdf.set_text_color(245, 158, 11)
    else:
        pdf.set_text_color(16, 185, 129)
    pdf.cell(50, 6, _safe(f"{severity_val}/10 - {severity_lbl}"))

    conf_lbl = mb.get("confidence_label") or mb.get("confidence") or "Medium"
    if str(conf_lbl).lower() == "high":
        pdf.set_text_color(16, 185, 129)
    elif str(conf_lbl).lower() == "medium":
        pdf.set_text_color(245, 158, 11)
    else:
        pdf.set_text_color(239, 68, 68)
    pdf.cell(50, 6, _safe(str(conf_lbl).upper()))

    pdf.set_xy(12, start_y + 22)
    pdf.ln(4)

    # Insight block (blue tinted)
    pdf.set_fill_color(239, 246, 255)
    pdf.set_draw_color(191, 219, 254)
    pdf.set_font("helvetica", "I", 9.5)
    pdf.set_text_color(30, 58, 138)

    insight_text = _safe(mb.get("insight") or "No insight details registered.")
    label_text = _safe(f"Key Insight:\n{insight_text}")
    lines_count = len(pdf.multi_cell(186, 5, label_text, split_only=True))
    box_height = (lines_count * 5) + 6

    pdf.rect(12, pdf.get_y(), 186, box_height, "FD")
    pdf.set_xy(16, pdf.get_y() + 3)
    pdf.multi_cell(178, 5, label_text)

    pdf.ln(8)

    # ──────────────────────────────────────────────────────────────────────────
    # Section 2: KPIs Affected
    # ──────────────────────────────────────────────────────────────────────────
    draw_section_header("Section 2 - KPIs Affected")

    kpis = mb.get("kpis_affected") or []

    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("helvetica", "B", 9)

    col_widths = [60, 32, 32, 32, 30]
    cols = ["KPI / Metric", "Current Value", "Projected Value", "Delta %", "Direction"]

    pdf.set_x(12)
    for idx, col in enumerate(cols):
        pdf.cell(col_widths[idx], 8, col, border=1, align="C" if idx > 0 else "L", fill=True)
    pdf.ln()

    pdf.set_text_color(15, 23, 42)
    pdf.set_font("helvetica", "", 9)

    if not kpis:
        pdf.set_x(12)
        pdf.cell(186, 8, "No Key Performance Indicators affected.", border=1, align="C")
        pdf.ln()
    else:
        for idx, kpi in enumerate(kpis):
            bg = (idx % 2 == 1)
            if bg:
                pdf.set_fill_color(248, 250, 252)
            else:
                pdf.set_fill_color(255, 255, 255)

            direction = _safe(str(kpi.get("direction", "N/A")).upper())
            delta_pct = kpi.get("delta_pct") or kpi.get("delta") or 0.0
            unit = kpi.get("current_unit") or kpi.get("unit") or ""
            current_val = _safe(f"{kpi.get('current_value', '0')} {unit}".strip())
            projected_val = _safe(f"{kpi.get('projected_value', '0')} {unit}".strip())

            pdf.set_x(12)
            pdf.cell(col_widths[0], 8, _safe(f" {kpi.get('kpi', 'N/A')}"), border=1, fill=True)
            pdf.cell(col_widths[1], 8, current_val, border=1, align="C", fill=True)
            pdf.cell(col_widths[2], 8, projected_val, border=1, align="C", fill=True)

            pdf.set_font("helvetica", "B", 9)
            if "DOWN" in direction or (isinstance(delta_pct, (int, float)) and delta_pct < 0):
                pdf.set_text_color(239, 68, 68)
            elif "UP" in direction or (isinstance(delta_pct, (int, float)) and delta_pct > 0):
                pdf.set_text_color(16, 185, 129)
            else:
                pdf.set_text_color(100, 116, 139)

            delta_str = f"{delta_pct:+.1f}%" if isinstance(delta_pct, (int, float)) else _safe(str(delta_pct))
            pdf.cell(col_widths[3], 8, delta_str, border=1, align="C", fill=True)
            pdf.cell(col_widths[4], 8, direction, border=1, align="C", fill=True)

            pdf.set_text_color(15, 23, 42)
            pdf.set_font("helvetica", "", 9)
            pdf.ln()

    pdf.ln(8)

    # ──────────────────────────────────────────────────────────────────────────
    # Section 3: Recommended Action
    # ──────────────────────────────────────────────────────────────────────────
    draw_section_header("Section 3 - Recommended Action")

    top_action = mb.get("top_action") or {}
    action_type = _safe(str(top_action.get("action_type") or "Execute Protocol").upper().replace("_", " "))
    description = _safe(top_action.get("description") or "Initiate standard mitigation path.")
    timeline = _safe(str(top_action.get("timeline") or "Immediate"))

    savings_pkr = top_action.get("estimated_savings_pkr")
    if savings_pkr is not None:
        quantified_delta = _safe(f"PKR {savings_pkr:,.0f} estimated savings/benefit")
    else:
        quantified_delta = "Quantified delta not specified"

    justification = _safe(
        top_action.get("justification")
        or mb.get("context")
        or "Recommended based on autonomous analysis pipeline corroborating multiple metrics."
    )

    pdf.set_fill_color(250, 250, 250)
    pdf.set_draw_color(226, 232, 240)

    pdf.set_font("helvetica", "", 9.5)
    lines_count_just = len(pdf.multi_cell(178, 4.5, f"Justification: {justification}", split_only=True))
    lines_count_desc = len(pdf.multi_cell(178, 4.5, f"Description: {description}", split_only=True))

    total_action_height = 36 + (lines_count_just * 4.5) + (lines_count_desc * 4.5)

    if pdf.get_y() + total_action_height > 270:
        pdf.add_page()

    pdf.set_x(12)
    start_action_y = pdf.get_y()
    pdf.rect(12, start_action_y, 186, total_action_height, "FD")

    pdf.set_xy(16, start_action_y + 3)
    pdf.set_font("helvetica", "B", 10.5)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 6, f"RECOMMENDED PATH: {action_type}")

    pdf.set_font("helvetica", "", 9.5)
    pdf.set_text_color(15, 23, 42)

    pdf.set_xy(16, start_action_y + 11)
    pdf.multi_cell(178, 4.5, f"Description: {description}")

    pdf.set_x(16)
    pdf.multi_cell(178, 4.5, f"Justification: {justification}")

    current_y = pdf.get_y()
    pdf.set_xy(16, current_y + 2)
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(90, 5, _safe(f"QUANTIFIED DELTA: {quantified_delta}"))
    pdf.cell(90, 5, _safe(f"TIME TO EXECUTE: {timeline}"), align="R")

    pdf.set_xy(12, start_action_y + total_action_height)
    pdf.ln(8)

    # ──────────────────────────────────────────────────────────────────────────
    # Section 4: Agent Pipeline
    # ──────────────────────────────────────────────────────────────────────────
    if pdf.get_y() + 45 > 270:
        pdf.add_page()

    draw_section_header("Section 4 - Agent Pipeline Execution")

    pdf.set_font("helvetica", "B", 9)
    pdf.set_fill_color(241, 245, 249)
    pdf.set_draw_color(203, 213, 225)

    agents_order = ["ingestion", "research", "analysis", "decision", "execution"]

    pdf.set_x(12)
    start_agents_y = pdf.get_y()

    pdf.rect(12, start_agents_y, 186, 20, "FD")

    block_width = 186 / 5
    for idx, agent_name in enumerate(agents_order):
        time_taken = "N/A"
        for item in agent_times:
            if item["agent"] == agent_name:
                time_taken = item["time"]
                break

        pdf.set_xy(12 + (idx * block_width), start_agents_y + 2)
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(block_width, 5, agent_name.upper(), align="C")

        pdf.set_xy(12 + (idx * block_width), start_agents_y + 8)
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(99, 102, 241)
        pdf.cell(block_width, 6, "COMPLETED", align="C")

        pdf.set_xy(12 + (idx * block_width), start_agents_y + 14)
        pdf.set_font("helvetica", "", 8)
        pdf.set_text_color(148, 163, 184)
        pdf.cell(block_width, 4, f"Duration: {time_taken}", align="C")

        if idx < 4:
            pdf.set_draw_color(226, 232, 240)
            pdf.line(
                12 + ((idx + 1) * block_width), start_agents_y + 2,
                12 + ((idx + 1) * block_width), start_agents_y + 18
            )

    pdf.set_xy(12, start_agents_y + 20)

    return bytes(pdf.output())
